### PR TITLE
Added extensibility to service provider, controller, and model classes

### PR DESCRIPTION
**Pull request by unstoppablecarl**
added a config file allowing users to override/extend the PageCrudController and Page model classes.

### CODE REVIEW

**Comment by unstoppablecarl** [comment]
This new functionality needs to be documented in the readme. I wanted to see if this PR would be noticed before I bothered.

**Comment by njbarrett** [comment]
This would be really useful

**Comment by tabacitu** [comment]
Hi @unstoppablecarl ,

Sorry for taking this long to merge it - I've spent so much time on Backpack in 2016 that all my other endeavours have gone to shit - had to tone down Backpack to "urgent only" for a while.

This is a really great addition, I agree. Very clean PR, I tested it, merged it and added the readme instructions, as you said. I only made one small change - I renamed the config file from ```page-manager.php``` to ```pagemanager.php```, for consistency (already had ```permissionmanager.php```). If you have any thoughts about [the readme addition](https://github.com/Laravel-Backpack/PageManager#extend), do tell.

Thanks a lot, cheers!

**Comment by tabacitu** [comment]
Also, I think this sets a good precedent, and we should provide config files like this for all/most packages, so people could easily extend Controllers, Models and Requests. 

@OwenMelbz  - do you agree? Do you see any downsides?

**Pull request merged**
